### ISSUE TITLE
Change NodeName on a single node compose project to prepare for migration to k3s clustered

### ISSUE THREAD

**Issue by Hareet** [medic/couchdb-migration#20]
We are unable to complete clustering for an eCHIS project due to the following reasons:

The project was initially launched on docker compose as a single node couchdb using `couchdb@127.0.0.1` in vm.args as its NODE_NAME.

In order for us to cluster this project in k3s, we need to change NODE_NAME from couchdb@127.0.0.1 to couchdb@<k3s_service_name> prior to launching couch-migration and following steps to move-shards.

This happens because if we try to launch clustered couchdb with node1 being at couchdb@127.0.0.1, its unable to pass couchdb node1's url to the other couch's to be identifiable, and if we launch couchdb node1 with its new k3s service name inside docker compose to be able to run couch-migration, we run into `no shards can be opened` since our node name has changed.

[Relevant GH comment from jan](https://github.com/apache/couchdb/discussions/2949#discussioncomment-29060)

Here's the process we've identified that we need to do:
- We need to rename couchdb@127.0.0.1 to couchdb@couchdb-1.test-echis.svc.cluster.local on all db's while its running in compose
- We will error after changing _dbs endpoint to "no shards can be opened"
- Stop couchdb single node after the above change.
- Start up clustered couchdb in compose with container service names being the same as the k3s service resource we would use. This will enable node1 to be able to read couchdb data that we modified earlier
- Couch-migration should now work as-is and we can follow clustered instructions
- All metadata should be setup for k3s service names, and we can create k3s templates and deploy

Is it possible for us to use couch-migration or a branch to address change node name for a single node couchdb (in order to prepare it for clustering)? 

If done manually, is it okay to only change docs for medic, medic-sentinel, medic-client dbs at /_local / _dbs endpoint? There are 8895 db's, and we have about 5 projects that will go through this process. I also imagine the community would benefit from this as they cluster projects to k3s that were initially created via compose.

**Comment by Hareet** [comment]
I tried to create my own shard_matrix output from the docs

```
{
  "00000000-15555554": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "15555555-2aaaaaa9": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "2aaaaaaa-3ffffffe": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "3fffffff-55555553": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "55555554-6aaaaaa8": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "6aaaaaa9-7ffffffd": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "7ffffffe-95555552": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "95555553-aaaaaaa7": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "aaaaaaa8-bffffffc": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "bffffffd-d5555551": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "d5555552-eaaaaaa6": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "eaaaaaa7-ffffffff": "couchdb@couchdb-1.test-echis.svc.cluster.local"
}
```

and then running `run couchdb-migration move-shards $shard_matrix` but it errors

```
An unexpected error occurred SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/bin/move-shards.js:9:55
    at Object.<anonymous> (/app/bin/move-shards.js:17:3)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```
Could be something simple as messing up structure when I'm creating shard_matrix env variable?

Ideally, we would be able to custom create a shard_matrix variable and run move-shard command. That would be least amount of code edits.

**Comment by Hareet** [comment]
Created the shard_matrix env variable by:
- creating a file shard_matrix
- Putting modified output there
- export shard_matrix = `cat shard_matrix`
- echo $shard_matrix

```
investigator@echisiclone:~/cht$ echo "$shard_matrix"
{
  "00000000-15555554": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "15555555-2aaaaaa9": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "2aaaaaaa-3ffffffe": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "3fffffff-55555553": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "55555554-6aaaaaa8": "couchdb@couchdb-1.test-echissvc.cluster.local",
  "6aaaaaa9-7ffffffd": "couchdb@couchdb-1.test-echissvc.cluster.local",
  "7ffffffe-95555552": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "95555553-aaaaaaa7": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "aaaaaaa8-bffffffc": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "bffffffd-d5555551": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "d5555552-eaaaaaa6": "couchdb@couchdb-1.test-echis.svc.cluster.local",
  "eaaaaaa7-ffffffff": "couchdb@couchdb-1.test-echis.svc.cluster.local"
}
```
- sudo shard_matrix="$shard_matrix" docker compose -f migration.yml run couch-migration move-shards $shard_matrix

**Comment by Hareet** [comment]
This is resolved by [Gareth's comment here](https://github.com/apache/couchdb/discussions/2949#discussioncomment-29060)

last $shard_matrix needs to be in quotes "$shard_matrix"

Final command:
`sudo shard_matrix="$shard_matrix" docker compose -f migration.yml run couch-migration move-shards "$shard_matrix"`

**Comment by jonathanvq** [comment]
@Hareet, can this one be closed per your last comment? I'm going to assume yes; please re-open if needed. By the way, I don't know if the link you posted is what you meant. Is it correct?
